### ISSUE TITLE
Accept quoted column names in PRIMARY KEY declaration

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#7] opened 2017-08-15 00:43 UTC
The following create statement throws a `java.sql.SQLException: Error while parsing sql statement` error because quoted identifiers are not supported within the PRIMARY KEY.

```
create table `SomeTableName` (
`creation_instance` int64
) PRIMARY KEY (`creation_instance`)

```

The following **does** work
```
create table `SomeTableName` (
`creation_instance` int64
) PRIMARY KEY (creation_instance)
```

**Comment by olavloite** [comment] 2017-08-17 08:25
Caused by JSQLParser/JSqlParser#491 which has now been fixed

**Comment by olavloite** [comment] 2017-08-17 13:43
Fixed in version 0.12.

**Closed by olavloite** 2017-08-17 13:43 UTC
